export const REGD_USER_SUCCESS = "REGD_USER_SUCCESS"
export const REGD_USER_FAILURE = "REGD_USER_FAILURE"

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"
